<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Inertia\Inertia;
use Illuminate\Support\Facades\Storage;
use App\Services\AktivitasService;

class BackupController extends Controller
{
    public function index()
    {
        // List existing backup files from storage/app/backups
        $backupDir = storage_path('app/backups');
        $backups = [];

        if (is_dir($backupDir)) {
            $files = array_diff(scandir($backupDir, SCANDIR_SORT_DESCENDING), ['.', '..']);
            foreach ($files as $file) {
                $path = $backupDir . DIRECTORY_SEPARATOR . $file;
                $backups[] = [
                    'id' => md5($file),
                    'nama' => $file,
                    'ukuran' => $this->formatSize(filesize($path)),
                    'tanggal' => date('d M Y, H:i', filemtime($path)),
                    'jenis' => str_contains($file, 'full') ? 'Full System' : 'Database',
                    'status' => 'sukses',
                ];
            }
        }

        return Inertia::render('Sistem/Backup/Index', [
            'backups' => $backups,
        ]);
    }

    public function create()
    {
        $backupDir = storage_path('app/backups');
        if (!is_dir($backupDir)) {
            mkdir($backupDir, 0755, true);
        }

        $filename = 'backup_mysql_' . date('Ymd_His') . '.sql';
        $filepath = $backupDir . DIRECTORY_SEPARATOR . $filename;

        $dbHost = config('database.connections.mysql.host');
        $dbPort = config('database.connections.mysql.port');
        $dbUser = config('database.connections.mysql.username');
        $dbPass = config('database.connections.mysql.password');
        $dbName = config('database.connections.mysql.database');

        // Build mysqldump command - auto-discover WAMP MySQL path
        $mysqldumpCmd = 'mysqldump';
        $wampMysqlDir = 'C:\\wamp64\\bin\\mysql';
        if (is_dir($wampMysqlDir)) {
            $dirs = glob($wampMysqlDir . '\\mysql*', GLOB_ONLYDIR);
            // Sort descending to get latest version first
            rsort($dirs);
            foreach ($dirs as $dir) {
                $candidate = $dir . '\\bin\\mysqldump.exe';
                if (file_exists($candidate)) {
                    $mysqldumpCmd = "\"$candidate\"";
                    break;
                }
            }
        }

        $passwordPart = !empty($dbPass) ? " -p\"$dbPass\"" : "";
        $command = "$mysqldumpCmd -h $dbHost -P $dbPort -u $dbUser$passwordPart --routines --triggers $dbName > \"$filepath\" 2>&1";

        exec($command, $output, $returnCode);

        if (file_exists($filepath) && filesize($filepath) > 0) {
            $zipFilename = str_replace('.sql', '.zip', $filename);
            $zipPath = $backupDir . DIRECTORY_SEPARATOR . $zipFilename;
            $zip = new \ZipArchive();
            if ($zip->open($zipPath, \ZipArchive::CREATE) === TRUE) {
                $zip->addFile($filepath, $filename);
                $zip->close();
            }
            unlink($filepath); // Remove raw sql file

            AktivitasService::catat('Backup Database', null, null, null, ['file' => $zipFilename]);

            return back()->with('success', 'Backup berhasil dibuat: ' . $zipFilename);
        }

        // If mysqldump failed, try PHP-native backup approach
        return $this->phpNativeBackup($backupDir);
    }

    /**
     * PHP-native backup fallback when mysqldump is not available
     */
    private function phpNativeBackup($backupDir)
    {
        try {
            $filename = 'backup_mysql_' . date('Ymd_His') . '.sql';
            $filepath = $backupDir . DIRECTORY_SEPARATOR . $filename;
            
            $tables = \DB::select('SHOW TABLES');
            $dbName = config('database.connections.mysql.database');
            $key = 'Tables_in_' . $dbName;
            
            $sqlContent = "-- Backup generated by PHP on " . date('Y-m-d H:i:s') . "\n";
            $sqlContent .= "-- Database: $dbName\n\n";
            $sqlContent .= "SET FOREIGN_KEY_CHECKS=0;\n\n";

            foreach ($tables as $table) {
                $tableName = $table->$key;
                
                // Get CREATE TABLE statement
                $createTable = \DB::select("SHOW CREATE TABLE `$tableName`");
                $sqlContent .= "DROP TABLE IF EXISTS `$tableName`;\n";
                $sqlContent .= $createTable[0]->{'Create Table'} . ";\n\n";

                // Get all rows
                $rows = \DB::table($tableName)->get();
                if ($rows->count() > 0) {
                    foreach ($rows as $row) {
                        $values = array_map(function ($val) {
                            if (is_null($val)) return 'NULL';
                            return "'" . addslashes($val) . "'";
                        }, (array) $row);
                        $sqlContent .= "INSERT INTO `$tableName` VALUES (" . implode(', ', $values) . ");\n";
                    }
                    $sqlContent .= "\n";
                }
            }

            $sqlContent .= "SET FOREIGN_KEY_CHECKS=1;\n";
            
            file_put_contents($filepath, $sqlContent);

            // Zip it
            $zipFilename = str_replace('.sql', '.zip', $filename);
            $zipPath = $backupDir . DIRECTORY_SEPARATOR . $zipFilename;
            $zip = new \ZipArchive();
            if ($zip->open($zipPath, \ZipArchive::CREATE) === TRUE) {
                $zip->addFile($filepath, $filename);
                $zip->close();
            }
            unlink($filepath);

            AktivitasService::catat('Backup Database (PHP)', null, null, null, ['file' => $zipFilename]);

            return back()->with('success', 'Backup berhasil dibuat: ' . $zipFilename);
        } catch (\Exception $e) {
            return back()->with('error', 'Gagal membuat backup: ' . $e->getMessage());
        }
    }

    public function download($filename)
    {
        $path = storage_path('app/backups/' . $filename);
        if (file_exists($path)) {
            return response()->download($path);
        }
        return back()->with('error', 'File tidak ditemukan');
    }

    public function destroy($filename)
    {
        $path = storage_path('app/backups/' . $filename);
        if (file_exists($path)) {
            unlink($path);
            return back()->with('success', 'Backup berhasil dihapus');
        }
        return back()->with('error', 'File tidak ditemukan');
    }

    public function restore(Request $request)
    {
        $request->validate([
            'backup_file' => 'required|file|max:512000', // max 500MB
        ]);

        $file = $request->file('backup_file');
        $ext = strtolower($file->getClientOriginalExtension());

        try {
            $tempSqlPath = storage_path('app/backups/temp_restore_' . time() . '.sql');

            if ($ext === 'zip') {
                $zip = new \ZipArchive();
                if ($zip->open($file->getPathname()) === TRUE) {
                    // Find the .sql file inside the zip
                    $sqlFile = null;
                    for ($i = 0; $i < $zip->numFiles; $i++) {
                        $name = $zip->getNameIndex($i);
                        if (str_ends_with(strtolower($name), '.sql')) {
                            $sqlFile = $name;
                            break;
                        }
                    }
                    if (!$sqlFile) {
                        $zip->close();
                        return back()->with('error', 'Tidak ditemukan file .sql di dalam arsip ZIP');
                    }
                    $sqlContent = $zip->getFromName($sqlFile);
                    $zip->close();
                    file_put_contents($tempSqlPath, $sqlContent);
                } else {
                    return back()->with('error', 'Gagal membuka file ZIP');
                }
            } elseif ($ext === 'sql') {
                copy($file->getPathname(), $tempSqlPath);
            } else {
                return back()->with('error', 'Format file tidak didukung. Gunakan .sql atau .zip');
            }

            if (!file_exists($tempSqlPath) || filesize($tempSqlPath) === 0) {
                @unlink($tempSqlPath);
                return back()->with('error', 'File backup kosong atau tidak valid');
            }

            // Try using mysql CLI first (most reliable)
            $restored = $this->restoreViaCli($tempSqlPath);

            if (!$restored) {
                // Fallback: PHP-based restore
                $this->restoreViaPhp($tempSqlPath);
            }

            @unlink($tempSqlPath);

            AktivitasService::catat('Restore Database', null, null, null, ['file' => $file->getClientOriginalName()]);

            return back()->with('success', 'Restore berhasil! Database telah dipulihkan.');
        } catch (\Exception $e) {
            @unlink($tempSqlPath ?? '');
            \DB::statement('SET FOREIGN_KEY_CHECKS=1');
            return back()->with('error', 'Gagal restore: ' . $e->getMessage());
        }
    }

    /**
     * Restore database using mysql CLI tool
     */
    private function restoreViaCli($sqlFilePath)
    {
        $dbHost = config('database.connections.mysql.host');
        $dbPort = config('database.connections.mysql.port');
        $dbUser = config('database.connections.mysql.username');
        $dbPass = config('database.connections.mysql.password');
        $dbName = config('database.connections.mysql.database');

        // Find mysql executable
        $mysqlCmd = 'mysql';
        $wampMysqlDir = 'C:\\wamp64\\bin\\mysql';
        if (is_dir($wampMysqlDir)) {
            $dirs = glob($wampMysqlDir . '\\mysql*', GLOB_ONLYDIR);
            rsort($dirs);
            foreach ($dirs as $dir) {
                $candidate = $dir . '\\bin\\mysql.exe';
                if (file_exists($candidate)) {
                    $mysqlCmd = "\"$candidate\"";
                    break;
                }
            }
        }

        $passwordPart = !empty($dbPass) ? " -p\"$dbPass\"" : "";
        $command = "$mysqlCmd -h $dbHost -P $dbPort -u $dbUser$passwordPart $dbName < \"$sqlFilePath\" 2>&1";

        exec($command, $output, $returnCode);

        return $returnCode === 0;
    }

    /**
     * Restore database using PHP (fallback)
     */
    private function restoreViaPhp($sqlFilePath)
    {
        $sqlContent = file_get_contents($sqlFilePath);

        \DB::statement('SET FOREIGN_KEY_CHECKS=0');

        // Properly split SQL statements, handling multi-line statements
        $statements = [];
        $current = '';
        $lines = explode("\n", $sqlContent);

        foreach ($lines as $line) {
            $trimmed = trim($line);

            // Skip comments and empty lines
            if (empty($trimmed) || str_starts_with($trimmed, '--') || str_starts_with($trimmed, '/*')) {
                // But handle /*!...*/ MySQL conditional comments - they may contain executable SQL
                if (str_starts_with($trimmed, '/*!') && str_ends_with($trimmed, '*/;')) {
                    $statements[] = $trimmed;
                }
                continue;
            }

            $current .= $line . "\n";

            // Check if statement is complete (ends with semicolon)
            if (str_ends_with($trimmed, ';')) {
                $stmt = trim($current);
                if (!empty($stmt)) {
                    $statements[] = $stmt;
                }
                $current = '';
            }
        }

        // Execute any remaining statement
        if (!empty(trim($current))) {
            $statements[] = trim($current);
        }

        foreach ($statements as $statement) {
            $clean = trim($statement);
            if (!empty($clean) && !str_starts_with($clean, '--')) {
                // Remove trailing semicolon for unprepared (PDO adds it)
                \DB::unprepared($clean);
            }
        }

        \DB::statement('SET FOREIGN_KEY_CHECKS=1');
    }

    private function formatSize($bytes)
    {
        $units = ['B', 'KB', 'MB', 'GB'];
        $i = 0;
        while ($bytes >= 1024 && $i < count($units) - 1) {
            $bytes /= 1024;
            $i++;
        }
        return round($bytes, 2) . ' ' . $units[$i];
    }
}
